@echo off
echo Killing all Node.js processes...
taskkill /F /IM node.exe /T

echo Cleaning Next.js cache...
if exist ".next" rd /s /q ".next"

echo Installing dependencies...
call npm install

echo Starting development server...
call npm run dev 